# -*- coding: utf-8 -*-
"""catdetection111.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKGSgpCXP0u6jyAf8n4uc36b5ckLTm8m
"""

!wget https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip

import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd
import numpy as np
import random
import warnings
warnings.filterwarnings('ignore')
import os
from keras.preprocessing.image import load_img

!unzip kagglecatsanddogs_5340.zip

input_path=[]
label=[]
for class_name in os.listdir("PetImages"):
  for path in os.listdir("PetImages/"+class_name):
    if class_name == 'Cat':
       label.append(0)
    else:
       label.append(1)
    input_path.append(os.path.join("PetImages",class_name,path))
print(input_path[0],label[0])

len(input_path)

df = pd.DataFrame()
df['images'] = input_path
df['label'] = label
df = df.sample(frac=1).reset_index(drop=True)
df.head()

for i in df['images']:
  if '.jpg' not in i:
    print(i)

import PIL
l=[]
for image in df['images']:
  try:
    img=PIL.Image.open(image)
  except:
     l.append(image)

l

df = df[df['images']!='PetImages/Dog/Thumbs.db']
df = df[df['images']!='PetImages/Cat/Thumbs.db']
df = df[df['images']!='PetImages/Cat/666.jpg']
df = df[df['images']!='PetImages/Dog/11702.jpg']
len(df)

plt.figure(figsize=(25,25))
temp = df[df['label']==0]['images']
start = random.randint(0,len(temp))
files = temp[start:start+25]
for index, file in enumerate(files):
  plt.subplot(5,5,index+1)
  img=load_img(file)
  img=np.array(img)
  plt.imshow(img)
  plt.title("Cats")
  plt.axis("off")















